
public enum Specializare {
    CARDIOLOGIE,
    ONCOLOGIE,
    NEUROLOGIE,
    PEDIATRIE,
    DERMATOLOGIE,
    GINECOLOGIE,
    UROLOGIE,
    ORTOPEDIE,
    OFTALMOLOGIE,
    ORL,
    REUMATOLOGIE,
    ENDOCRINOLOGIE,
    GASTROENTEROLOGIE,
    HEMATOLOGIE,
    NEFROLOGIE,
    CHIRURGIE_GENERALA,
    MEDICINA_INTERNA,
    ALERGOLOGIE,
    MEDICINA_DE_FAMILIE;
}